"""Declarative base + shared column mixins. Imports every model so Alembic sees them."""
from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import TIMESTAMP, func, text
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Root declarative base for all ORM models."""


class UUIDPKMixin:
    """UUID primary key generated by PostgreSQL `gen_random_uuid()`."""

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        server_default=text("gen_random_uuid()"),
    )


class TimestampMixin:
    """`created_at` / `updated_at` maintained by the DB + ORM `onupdate`."""

    created_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        TIMESTAMP(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )


# --- model registry: every model module is imported so `Base.metadata` is complete ---
# Populated incrementally across DB-03..DB-05; Alembic autogenerate depends on this.
from app.db import registry  # noqa: E402,F401
