"""initial_schema

Revision ID: 0001
Revises: 
Create Date: 2026-07-12 11:51:33.523830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0001'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # trip_code_seq feeds app-generated TRP-#### codes (BE-07). Autogenerate
    # does not emit standalone sequences, so create it explicitly here.
    op.execute("CREATE SEQUENCE IF NOT EXISTS trip_code_seq START 1")
    op.create_table('drivers',
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('license_number', sa.String(length=30), nullable=False),
    sa.Column('license_category', sa.String(length=10), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=False),
    sa.Column('contact_number', sa.String(length=15), nullable=False),
    sa.Column('safety_score', sa.Numeric(precision=5, scale=2), server_default=sa.text('100'), nullable=False),
    sa.Column('status', sa.Enum('available', 'on_trip', 'off_duty', 'suspended', name='driver_status'), server_default=sa.text("'available'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("contact_number ~ '^[0-9+][0-9 -]{7,14}$'", name='ck_drivers_contact'),
    sa.CheckConstraint('safety_score BETWEEN 0 AND 100', name='ck_drivers_safety_score'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index('ix_drivers_license_expiry', 'drivers', ['license_expiry'], unique=False)
    op.create_index('ix_drivers_status', 'drivers', ['status'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('role', sa.Enum('fleet_manager', 'driver', 'safety_officer', 'financial_analyst', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("email ~* '^[A-Za-z0-9._%%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$'", name='ck_users_email'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('vehicles',
    sa.Column('registration_number', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('type', sa.Enum('truck', 'van', 'mini_truck', 'trailer', name='vehicle_type'), nullable=False),
    sa.Column('max_load_capacity_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('odometer_km', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('acquisition_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('status', sa.Enum('available', 'on_trip', 'in_shop', 'retired', name='vehicle_status'), server_default=sa.text("'available'"), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('acquisition_cost > 0', name='ck_vehicles_acqcost_pos'),
    sa.CheckConstraint('max_load_capacity_kg > 0', name='ck_vehicles_capacity_pos'),
    sa.CheckConstraint('odometer_km >= 0', name='ck_vehicles_odometer_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('registration_number')
    )
    op.create_index('ix_vehicles_status', 'vehicles', ['status'], unique=False)
    op.create_index('ix_vehicles_type_region', 'vehicles', ['type', 'region'], unique=False)
    op.create_table('ai_settings',
    sa.Column('id', sa.SmallInteger(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('chatbot_enabled', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('model', sa.String(length=80), server_default=sa.text("'anthropic/claude-3.5-haiku'"), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), server_default=sa.text('0.30'), nullable=False),
    sa.Column('max_tokens', sa.Integer(), server_default=sa.text('1024'), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('role_tool_permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('id = 1', name='ck_ai_settings_singleton'),
    sa.CheckConstraint('max_tokens BETWEEN 128 AND 8192', name='ck_ai_settings_max_tokens'),
    sa.CheckConstraint('temperature BETWEEN 0 AND 2', name='ck_ai_settings_temperature'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=60), nullable=False),
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), server_default=sa.text("'New chat'"), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('maintenance_logs',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('open', 'closed', name='maintenance_status'), server_default=sa.text("'open'"), nullable=False),
    sa.Column('opened_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint("status <> 'closed' OR closed_at IS NOT NULL", name='ck_maint_closed'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_maint_vehicle', 'maintenance_logs', ['vehicle_id'], unique=False)
    op.create_index('uq_maint_open_per_vehicle', 'maintenance_logs', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'open'"))
    op.create_table('trips',
    sa.Column('trip_code', sa.String(length=12), nullable=False),
    sa.Column('source', sa.String(length=120), nullable=False),
    sa.Column('destination', sa.String(length=120), nullable=False),
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.UUID(), nullable=False),
    sa.Column('cargo_weight_kg', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('planned_distance_km', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=14, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'dispatched', 'completed', 'cancelled', name='trip_status'), server_default=sa.text("'draft'"), nullable=False),
    sa.Column('start_odometer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('end_odometer', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('dispatched_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status <> 'completed' OR (start_odometer IS NOT NULL AND end_odometer IS NOT NULL)", name='ck_trips_completed_fields'),
    sa.CheckConstraint('end_odometer IS NULL OR start_odometer IS NULL OR end_odometer >= start_odometer', name='ck_trips_odometer'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['drivers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('trip_code')
    )
    op.create_index('ix_trips_driver', 'trips', ['driver_id'], unique=False)
    op.create_index('ix_trips_status', 'trips', ['status'], unique=False)
    op.create_index('ix_trips_vehicle', 'trips', ['vehicle_id'], unique=False)
    op.create_index('uq_trips_active_driver', 'trips', ['driver_id'], unique=True, postgresql_where=sa.text("status = 'dispatched'"))
    op.create_index('uq_trips_active_vehicle', 'trips', ['vehicle_id'], unique=True, postgresql_where=sa.text("status = 'dispatched'"))
    op.create_table('chat_messages',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('user', 'assistant', 'tool', name='chat_role'), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_chat_messages_session', 'chat_messages', ['session_id', 'created_at'], unique=False)
    op.create_table('expenses',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('toll', 'parking', 'fine', 'loading', 'other', name='expense_type'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('incurred_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('amount > 0', name='ck_expenses_amount_pos'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_expenses_vehicle_date', 'expenses', ['vehicle_id', 'incurred_at'], unique=False)
    op.create_table('fuel_logs',
    sa.Column('vehicle_id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=True),
    sa.Column('liters', sa.Numeric(precision=8, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('odometer_at_fill', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('filled_at', sa.Date(), server_default=sa.text('CURRENT_DATE'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.CheckConstraint('cost >= 0', name='ck_fuel_cost_nonneg'),
    sa.CheckConstraint('liters > 0', name='ck_fuel_liters_pos'),
    sa.CheckConstraint('odometer_at_fill IS NULL OR odometer_at_fill >= 0', name='ck_fuel_odometer_nonneg'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_fuel_vehicle_date', 'fuel_logs', ['vehicle_id', 'filled_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_fuel_vehicle_date', table_name='fuel_logs')
    op.drop_table('fuel_logs')
    op.drop_index('ix_expenses_vehicle_date', table_name='expenses')
    op.drop_table('expenses')
    op.drop_index('ix_chat_messages_session', table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index('uq_trips_active_vehicle', table_name='trips', postgresql_where=sa.text("status = 'dispatched'"))
    op.drop_index('uq_trips_active_driver', table_name='trips', postgresql_where=sa.text("status = 'dispatched'"))
    op.drop_index('ix_trips_vehicle', table_name='trips')
    op.drop_index('ix_trips_status', table_name='trips')
    op.drop_index('ix_trips_driver', table_name='trips')
    op.drop_table('trips')
    op.drop_index('uq_maint_open_per_vehicle', table_name='maintenance_logs', postgresql_where=sa.text("status = 'open'"))
    op.drop_index('ix_maint_vehicle', table_name='maintenance_logs')
    op.drop_table('maintenance_logs')
    op.drop_table('chat_sessions')
    op.drop_table('audit_logs')
    op.drop_table('ai_settings')
    op.drop_index('ix_vehicles_type_region', table_name='vehicles')
    op.drop_index('ix_vehicles_status', table_name='vehicles')
    op.drop_table('vehicles')
    op.drop_table('users')
    op.drop_index('ix_drivers_status', table_name='drivers')
    op.drop_index('ix_drivers_license_expiry', table_name='drivers')
    op.drop_table('drivers')
    # ### end Alembic commands ###
    # Drop the sequence and ENUM types so a re-upgrade after `downgrade base`
    # does not fail with "type already exists" (DB-06 round-trip proof).
    op.execute("DROP SEQUENCE IF EXISTS trip_code_seq")
    for _enum in (
        "user_role", "vehicle_type", "vehicle_status", "driver_status",
        "trip_status", "maintenance_status", "expense_type", "chat_role",
    ):
        op.execute(f"DROP TYPE IF EXISTS {_enum}")
